### ISSUE TITLE
java.Lang.NullPointerException on adding player to town

### ISSUE THREAD

**Issue by lucasboss45** [TheDGOfficial/SharpSK#3]
```
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! [Skript] Severe Error:
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Something went horribly wrong with Skript.
[14:13:00 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:13:00 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:13:00 ERROR]: #!#! Here is full list of them:
[14:13:00 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) ThatPacketAddon (tlatoani.us/thatpacketaddon) Tablisknu (tlatoani.us/tablisknu) Skellett (https://forums.skunity.com/resources/skellett.24/) SharpSK skript-db SkriptJSON skript-mirror (https://github.com/btk5h/skript-mirror) skDragon SkBee skUtilities (https://tim740.github.io/) SkQuery
[14:13:00 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:13:00 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:13:00 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:13:00 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:13:00 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:13:00 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Stack trace:
[14:13:00 ERROR]: #!#! java.lang.NullPointerException
[14:13:00 ERROR]: #!#!     at me.sharpjaws.sharpsk.hooks.Towny.EffTownyAddPlayerToTown.execute(EffTownyAddPlayerToTown.java:40)
[14:13:00 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[14:13:00 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:13:00 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:13:00 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:277)
[14:13:00 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onServerCommand(Commands.java:178)
[14:13:00 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[14:13:00 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:13:00 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:13:00 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[14:13:00 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:464)
[14:13:00 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[14:13:00 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173)
[14:13:00 ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
[14:13:00 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Version Information:
[14:13:00 ERROR]: #!#!   Skript: 2.4.1 (latest)
[14:13:00 ERROR]: #!#!     Flavor: skriptlang-github
[14:13:00 ERROR]: #!#!     Date: 2019-12-22
[14:13:00 ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[14:13:00 ERROR]: #!#!   Minecraft: 1.15.2
[14:13:00 ERROR]: #!#!   Java: 1.8.0_252 (OpenJDK 64-Bit Server VM 25.252-b09)
[14:13:00 ERROR]: #!#!   OS: Linux amd64 4.15.0-109-generic
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Server platform: Paper
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Current node: null
[14:13:00 ERROR]: #!#! Current item: [towny] Add %offlineplayer% to [town] %string%
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Thread: Server thread
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! Language: english
[14:13:00 ERROR]: #!#! Link parse mode: DISABLED
[14:13:00 ERROR]: #!#!
[14:13:00 ERROR]: #!#! End of Error.
[14:13:00 ERROR]: #!#!
```

Towny version 0.96.2.0

Syntax used:
`add {yes} to town "TownName"`

**Comment by TheDGOfficial** [comment]
Sorry, I was very busy and the notification of this issue is either not shown to me or I missed it somehow.  It is an easy fix. The original author forget to set the town name expression. See #5
